[world]
name = "Warpack Masters"
seed = "dev"

[world.socials]
x = "https://x.com/WarpackMasters"
discord = "https://discord.gg/tjJJHc7JtP"
github = "https://github.com/0xasten/warpack-Masters/"
telegram = ""

[namespace]
default = "Warpacks"

[env]
rpc_url = "https://api.cartridge.gg/x/warpacks-0-2-1/katana"
# Default account for katana with seed = 0
account_address = "0x5e14af9ed55fdd518e8bacf30a89e12c8450f9b6dd387f6bb6aff7903a7d40d"
private_key = "0x1d105d613aae948c2da77aebb2c346ccb02c8d9c4a3e31d5e9c504dda9f2924"

[writers]
"Warpacks" = ["Warpacks-actions", "Warpacks-dummy_system", "Warpacks-fight_system", "Warpacks-item_system", "Warpacks-shop_system", "Warpacks-recipe_system"]