[world]
name = "Warpack Masters"
seed = "dev"

[world.socials]
x = "https://x.com/WarpackMasters"
discord = "https://discord.gg/tjJJHc7JtP"
github = "https://github.com/0xasten/warpack-Masters/"
telegram = ""

[namespace]
default = "Warpacks"

[env]
rpc_url = ""
# Default account for katana with seed = 0
account_address = ""
private_key = ""
