[world]
name = "Warpack Masters"
description = "Warpack Masters is a competitive Player-versus-Player (PvP) game that combines inventory management and autobattler mechanics within a captivating fantasy theme."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://impulsedao.xyz/warpacks/"
seed = "warpack_masters"

[world.socials]
x = "https://x.com/WarpackMasters"
discord = "https://discord.gg/tjJJHc7JtP"
github = "https://github.com/0xasten/warpack-Masters/"
telegram = ""

[namespace]
default = "Warpacks"

[env]
rpc_url = ""
# Default account for katana with seed = 0
account_address = ""
private_key = ""

[writers]
"Warpacks" = ["Warpacks-actions", "Warpacks-dummy_system", "Warpacks-fight_system", 
    "Warpacks-item_system", "Warpacks-shop_system", "Warpacks-recipe_system", "Warpacks-config_system"]

[init_call_args]
"Warpacks-config_system" = ["0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"]

[migration]
skip_contracts = [
    "warpack_masters::externals::erc20",
]