[world]
name = "Warpack Masters"
description = "Warpack Masters is a competitive Player-versus-Player (PvP) game that combines inventory management and autobattler mechanics within a captivating fantasy theme."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://impulsedao.xyz/warpacks/"
seed = "warpack_masters"

[world.socials]
x = "https://x.com/WarpackMasters"
discord = "https://discord.gg/tjJJHc7JtP"
github = "https://github.com/0xasten/warpack-Masters/"
telegram = ""

[namespace]
default = "Warpacks"

[env]
rpc_url = ""
# Default account for katana with seed = 0
account_address = ""
private_key = ""
