[package]
cairo-version = "=2.9.4"
name = "warpack_masters"
version = "1.0.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.4.0" }

[dev-dependencies]
cairo_test = "=2.9.4"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.4.0" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]