[package]
cairo-version = "2.5.4"
name = "warpack_masters"
version = "0.6.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/warpack-master/katana"
account_address = "0x565fd2bceb42d6a6e867b2d8b3608e562cf1583d0c97240d2bb39da2ba4c456"
private_key = "0x5f72532149b8419c4cdeb2a983944fbd85ce13866e8ed01c950b05db302d97e"

#rpc_url = "http://0.0.0.0:5050"
#account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
#private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"

[tool.dojo.world]
name = "Warpack Masters"
description = "Warpack Masters is a competitive Player-versus-Player (PvP) game that combines inventory management and autobattler mechanics within a captivating fantasy theme."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://twitter.com/WarpackMasters"

[tool.dojo.world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"
