[package]
cairo-version = "2.10.1"
name = "warpack_masters"
version = "1.3.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dependencies]
openzeppelin_token = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v1.0.0" }
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v1.0.0" }
openzeppelin_access = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v1.0.0" }
openzeppelin_upgrades = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v1.0.0" }
dojo = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.6.0-alpha.2" }
starknet = "2.10.1"

[dev-dependencies]
cairo_test = "2.10.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.6.0-alpha.2" }
