[package]
cairo-version = "=2.7.0-rc.3"
name = "warpack_masters"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.4" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]

[tool.dojo.world]
name = "Warpack Masters"
description = "Warpack Masters is a competitive Player-versus-Player (PvP) game that combines inventory management and autobattler mechanics within a captivating fantasy theme."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://twitter.com/WarpackMasters"
seed = "warpack_masters"
namespace = { default = "Warpacks" }


[tool.dojo.world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"
