[package]
cairo-version = "=2.9.2"
name = "warpack_masters"
version = "0.2.5"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.3.1" }

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.3.1" }

[[target.starknet-contract]]

sierra = true

build-external-contracts = ["dojo::world::world_contract::world"]