use warpack_masters::systems::item::{item_system, IItemDispatcher, IItemDispatcherTrait};
use warpack_masters::{items};

fn add_items(ref item_system: IItemDispatcher) {
    item_system
        .add_item(
            items::Backpack::id,
            items::Backpack::name,
            items::Backpack::itemType,
            items::Backpack::rarity,
            items::Backpack::width,
            items::Backpack::height,
            items::Backpack::price,
            items::Backpack::effectType,
            items::Backpack::effectStacks,
            items::Backpack::effectActivationType,
            items::Backpack::chance,
            items::Backpack::cooldown,
            items::Backpack::energyCost,
            items::Backpack::isPlugin,
        );

    item_system
        .add_item(
            items::Pack::id,
            items::Pack::name,
            items::Pack::itemType,
            items::Pack::rarity,
            items::Pack::width,
            items::Pack::height,
            items::Pack::price,
            items::Pack::effectType,
            items::Pack::effectStacks,
            items::Pack::effectActivationType,
            items::Pack::chance,
            items::Pack::cooldown,
            items::Pack::energyCost,
            items::Pack::isPlugin,
        );

    item_system
        .add_item(
            items::Satchel::id,
            items::Satchel::name,
            items::Satchel::itemType,
            items::Satchel::rarity,
            items::Satchel::width,
            items::Satchel::height,
            items::Satchel::price,
            items::Satchel::effectType,
            items::Satchel::effectStacks,
            items::Satchel::effectActivationType,
            items::Satchel::chance,
            items::Satchel::cooldown,
            items::Satchel::energyCost,
            items::Satchel::isPlugin,
        );

    item_system
        .add_item(
            items::Pouch::id,
            items::Pouch::name,
            items::Pouch::itemType,
            items::Pouch::rarity,
            items::Pouch::width,
            items::Pouch::height,
            items::Pouch::price,
            items::Pouch::effectType,
            items::Pouch::effectStacks,
            items::Pouch::effectActivationType,
            items::Pouch::chance,
            items::Pouch::cooldown,
            items::Pouch::energyCost,
            items::Pouch::isPlugin,
        );

    item_system
        .add_item(
            items::Herb::id,
            items::Herb::name,
            items::Herb::itemType,
            items::Herb::rarity,
            items::Herb::width,
            items::Herb::height,
            items::Herb::price,
            items::Herb::effectType,
            items::Herb::effectStacks,
            items::Herb::effectActivationType,
            items::Herb::chance,
            items::Herb::cooldown,
            items::Herb::energyCost,
            items::Herb::isPlugin,
        );

    item_system
        .add_item(
            items::Dagger::id,
            items::Dagger::name,
            items::Dagger::itemType,
            items::Dagger::rarity,
            items::Dagger::width,
            items::Dagger::height,
            items::Dagger::price,
            items::Dagger::effectType,
            items::Dagger::effectStacks,
            items::Dagger::effectActivationType,
            items::Dagger::chance,
            items::Dagger::cooldown,
            items::Dagger::energyCost,
            items::Dagger::isPlugin,
        );

    item_system
        .add_item(
            items::Sword::id,
            items::Sword::name,
            items::Sword::itemType,
            items::Sword::rarity,
            items::Sword::width,
            items::Sword::height,
            items::Sword::price,
            items::Sword::effectType,
            items::Sword::effectStacks,
            items::Sword::effectActivationType,
            items::Sword::chance,
            items::Sword::cooldown,
            items::Sword::energyCost,
            items::Sword::isPlugin,
        );

    item_system
        .add_item(
            items::Spike::id,
            items::Spike::name,
            items::Spike::itemType,
            items::Spike::rarity,
            items::Spike::width,
            items::Spike::height,
            items::Spike::price,
            items::Spike::effectType,
            items::Spike::effectStacks,
            items::Spike::effectActivationType,
            items::Spike::chance,
            items::Spike::cooldown,
            items::Spike::energyCost,
            items::Spike::isPlugin,
        );

    item_system
        .add_item(
            items::Shield::id,
            items::Shield::name,
            items::Shield::itemType,
            items::Shield::rarity,
            items::Shield::width,
            items::Shield::height,
            items::Shield::price,
            items::Shield::effectType,
            items::Shield::effectStacks,
            items::Shield::effectActivationType,
            items::Shield::chance,
            items::Shield::cooldown,
            items::Shield::energyCost,
            items::Shield::isPlugin,
        );

    item_system
        .add_item(
            items::Helmet::id,
            items::Helmet::name,
            items::Helmet::itemType,
            items::Helmet::rarity,
            items::Helmet::width,
            items::Helmet::height,
            items::Helmet::price,
            items::Helmet::effectType,
            items::Helmet::effectStacks,
            items::Helmet::effectActivationType,
            items::Helmet::chance,
            items::Helmet::cooldown,
            items::Helmet::energyCost,
            items::Helmet::isPlugin,
        );

    item_system
        .add_item(
            items::HealingPotion::id,
            items::HealingPotion::name,
            items::HealingPotion::itemType,
            items::HealingPotion::rarity,
            items::HealingPotion::width,
            items::HealingPotion::height,
            items::HealingPotion::price,
            items::HealingPotion::effectType,
            items::HealingPotion::effectStacks,
            items::HealingPotion::effectActivationType,
            items::HealingPotion::chance,
            items::HealingPotion::cooldown,
            items::HealingPotion::energyCost,
            items::HealingPotion::isPlugin,
        );

    item_system
        .add_item(
            items::LeatherArmor::id,
            items::LeatherArmor::name,
            items::LeatherArmor::itemType,
            items::LeatherArmor::rarity,
            items::LeatherArmor::width,
            items::LeatherArmor::height,
            items::LeatherArmor::price,
            items::LeatherArmor::effectType,
            items::LeatherArmor::effectStacks,
            items::LeatherArmor::effectActivationType,
            items::LeatherArmor::chance,
            items::LeatherArmor::cooldown,
            items::LeatherArmor::energyCost,
            items::LeatherArmor::isPlugin,
        );

    item_system
        .add_item(
            items::Poison::id,
            items::Poison::name,
            items::Poison::itemType,
            items::Poison::rarity,
            items::Poison::width,
            items::Poison::height,
            items::Poison::price,
            items::Poison::effectType,
            items::Poison::effectStacks,
            items::Poison::effectActivationType,
            items::Poison::chance,
            items::Poison::cooldown,
            items::Poison::energyCost,
            items::Poison::isPlugin,
        );

    item_system
        .add_item(
            items::AugmentedSword::id,
            items::AugmentedSword::name,
            items::AugmentedSword::itemType,
            items::AugmentedSword::rarity,
            items::AugmentedSword::width,
            items::AugmentedSword::height,
            items::AugmentedSword::price,
            items::AugmentedSword::effectType,
            items::AugmentedSword::effectStacks,
            items::AugmentedSword::effectActivationType,
            items::AugmentedSword::chance,
            items::AugmentedSword::cooldown,
            items::AugmentedSword::energyCost,
            items::AugmentedSword::isPlugin,
        );

    item_system
        .add_item(
            items::AugmentedDagger::id,
            items::AugmentedDagger::name,
            items::AugmentedDagger::itemType,
            items::AugmentedDagger::rarity,
            items::AugmentedDagger::width,
            items::AugmentedDagger::height,
            items::AugmentedDagger::price,
            items::AugmentedDagger::effectType,
            items::AugmentedDagger::effectStacks,
            items::AugmentedDagger::effectActivationType,
            items::AugmentedDagger::chance,
            items::AugmentedDagger::cooldown,
            items::AugmentedDagger::energyCost,
            items::AugmentedDagger::isPlugin,
        );

    item_system
        .add_item(
            items::SpikeShield::id,
            items::SpikeShield::name,
            items::SpikeShield::itemType,
            items::SpikeShield::rarity,
            items::SpikeShield::width,
            items::SpikeShield::height,
            items::SpikeShield::price,
            items::SpikeShield::effectType,
            items::SpikeShield::effectStacks,
            items::SpikeShield::effectActivationType,
            items::SpikeShield::chance,
            items::SpikeShield::cooldown,
            items::SpikeShield::energyCost,
            items::SpikeShield::isPlugin,
        );
}

