use warpack_masters::{systems::{actions::{actions, IActionsDispatcher, IActionsDispatcherTrait}}};
use warpack_masters::{items};


fn add_items(ref actions_system: IActionsDispatcher) {
    actions_system
        .add_item(
            items::item_one_id,
            items::item_one_name,
            items::item_one_itemType,
            items::item_one_width,
            items::item_one_height,
            items::item_one_price,
            items::item_one_damage,
            items::item_one_chance,
            items::item_one_cooldown,
            items::item_one_rarity,
            items::item_one_armor,
            items::item_one_armorActivation,
            items::item_one_regen,
            items::item_one_regenActivation,
            items::item_one_reflect,
            items::item_one_reflectActivation,
            items::item_one_poison,
            items::item_one_poisonActivation,
        );

    actions_system
        .add_item(
            items::item_two_id,
            items::item_two_name,
            items::item_two_itemType,
            items::item_two_width,
            items::item_two_height,
            items::item_two_price,
            items::item_two_damage,
            items::item_two_chance,
            items::item_two_cooldown,
            items::item_two_rarity,
            items::item_two_armor,
            items::item_two_armorActivation,
            items::item_two_regen,
            items::item_two_regenActivation,
            items::item_two_reflect,
            items::item_two_reflectActivation,
            items::item_two_poison,
            items::item_two_poisonActivation,
        );

    actions_system
        .add_item(
            items::item_three_id,
            items::item_three_name,
            items::item_three_itemType,
            items::item_three_width,
            items::item_three_height,
            items::item_three_price,
            items::item_three_damage,
            items::item_three_chance,
            items::item_three_cooldown,
            items::item_three_rarity,
            items::item_three_armor,
            items::item_three_armorActivation,
            items::item_three_regen,
            items::item_three_regenActivation,
            items::item_three_reflect,
            items::item_three_reflectActivation,
            items::item_three_poison,
            items::item_three_poisonActivation,
        );

    actions_system
        .add_item(
            items::item_four_id,
            items::item_four_name,
            items::item_four_itemType,
            items::item_four_width,
            items::item_four_height,
            items::item_four_price,
            items::item_four_damage,
            items::item_four_chance,
            items::item_four_cooldown,
            items::item_four_rarity,
            items::item_four_armor,
            items::item_four_armorActivation,
            items::item_four_regen,
            items::item_four_regenActivation,
            items::item_four_reflect,
            items::item_four_reflectActivation,
            items::item_four_poison,
            items::item_four_poisonActivation,
        );

    actions_system
        .add_item(
            items::item_five_id,
            items::item_five_name,
            items::item_five_itemType,
            items::item_five_width,
            items::item_five_height,
            items::item_five_price,
            items::item_five_damage,
            items::item_five_chance,
            items::item_five_cooldown,
            items::item_five_rarity,
            items::item_five_armor,
            items::item_five_armorActivation,
            items::item_five_regen,
            items::item_five_regenActivation,
            items::item_five_reflect,
            items::item_five_reflectActivation,
            items::item_five_poison,
            items::item_five_poisonActivation,
        );

    actions_system
        .add_item(
            items::item_six_id,
            items::item_six_name,
            items::item_six_itemType,
            items::item_six_width,
            items::item_six_height,
            items::item_six_price,
            items::item_six_damage,
            items::item_six_chance,
            items::item_six_cooldown,
            items::item_six_rarity,
            items::item_six_armor,
            items::item_six_armorActivation,
            items::item_six_regen,
            items::item_six_regenActivation,
            items::item_six_reflect,
            items::item_six_reflectActivation,
            items::item_six_poison,
            items::item_six_poisonActivation,
        );

    actions_system
        .add_item(
            items::item_seven_id,
            items::item_seven_name,
            items::item_seven_itemType,
            items::item_seven_width,
            items::item_seven_height,
            items::item_seven_price,
            items::item_seven_damage,
            items::item_seven_chance,
            items::item_seven_cooldown,
            items::item_seven_rarity,
            items::item_seven_armor,
            items::item_seven_armorActivation,
            items::item_seven_regen,
            items::item_seven_regenActivation,
            items::item_seven_reflect,
            items::item_seven_reflectActivation,
            items::item_seven_poison,
            items::item_seven_poisonActivation,
        );

    actions_system
        .add_item(
            items::item_eight_id,
            items::item_eight_name,
            items::item_eight_itemType,
            items::item_eight_width,
            items::item_eight_height,
            items::item_eight_price,
            items::item_eight_damage,
            items::item_eight_chance,
            items::item_eight_cooldown,
            items::item_eight_rarity,
            items::item_eight_armor,
            items::item_eight_armorActivation,
            items::item_eight_regen,
            items::item_eight_regenActivation,
            items::item_eight_reflect,
            items::item_eight_reflectActivation,
            items::item_eight_poison,
            items::item_eight_poisonActivation,
        );

    actions_system
        .add_item(
            items::item_nine_id,
            items::item_nine_name,
            items::item_nine_itemType,
            items::item_nine_width,
            items::item_nine_height,
            items::item_nine_price,
            items::item_nine_damage,
            items::item_nine_chance,
            items::item_nine_cooldown,
            items::item_nine_rarity,
            items::item_nine_armor,
            items::item_nine_armorActivation,
            items::item_nine_regen,
            items::item_nine_regenActivation,
            items::item_nine_reflect,
            items::item_nine_reflectActivation,
            items::item_nine_poison,
            items::item_nine_poisonActivation,
        );

    actions_system
        .add_item(
            items::item_ten_id,
            items::item_ten_name,
            items::item_ten_itemType,
            items::item_ten_width,
            items::item_ten_height,
            items::item_ten_price,
            items::item_ten_damage,
            items::item_ten_chance,
            items::item_ten_cooldown,
            items::item_ten_rarity,
            items::item_ten_armor,
            items::item_ten_armorActivation,
            items::item_ten_regen,
            items::item_ten_regenActivation,
            items::item_ten_reflect,
            items::item_ten_reflectActivation,
            items::item_ten_poison,
            items::item_ten_poisonActivation,
        );

    actions_system
        .add_item(
            items::item_eleven_id,
            items::item_eleven_name,
            items::item_eleven_itemType,
            items::item_eleven_width,
            items::item_eleven_height,
            items::item_eleven_price,
            items::item_eleven_damage,
            items::item_eleven_chance,
            items::item_eleven_cooldown,
            items::item_eleven_rarity,
            items::item_eleven_armor,
            items::item_eleven_armorActivation,
            items::item_eleven_regen,
            items::item_eleven_regenActivation,
            items::item_eleven_reflect,
            items::item_eleven_reflectActivation,
            items::item_eleven_poison,
            items::item_eleven_poisonActivation,
        );

    actions_system
        .add_item(
            items::item_twelve_id,
            items::item_twelve_name,
            items::item_twelve_itemType,
            items::item_twelve_width,
            items::item_twelve_height,
            items::item_twelve_price,
            items::item_twelve_damage,
            items::item_twelve_chance,
            items::item_twelve_cooldown,
            items::item_twelve_rarity,
            items::item_twelve_armor,
            items::item_twelve_armorActivation,
            items::item_twelve_regen,
            items::item_twelve_regenActivation,
            items::item_twelve_reflect,
            items::item_twelve_reflectActivation,
            items::item_twelve_poison,
            items::item_twelve_poisonActivation,
        );

    actions_system
        .add_item(
            items::item_thirteen_id,
            items::item_thirteen_name,
            items::item_thirteen_itemType,
            items::item_thirteen_width,
            items::item_thirteen_height,
            items::item_thirteen_price,
            items::item_thirteen_damage,
            items::item_thirteen_chance,
            items::item_thirteen_cooldown,
            items::item_thirteen_rarity,
            items::item_thirteen_armor,
            items::item_thirteen_armorActivation,
            items::item_thirteen_regen,
            items::item_thirteen_regenActivation,
            items::item_thirteen_reflect,
            items::item_thirteen_reflectActivation,
            items::item_thirteen_poison,
            items::item_thirteen_poisonActivation,
        );
}

