// Generated by dojo-bindgen on Mon, 15 Apr 2024 07:51:23 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;

// Type definition for `warpack_masters::models::backpack::Grid` struct
[Serializable]
public struct Grid {
    public uint x;
    public uint y;
}


// Model definition for `warpack_masters::models::backpack::Backpack` model
public class Backpack : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("grid")]
    public Grid grid;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        