// Generated by dojo-bindgen on Mon, 15 Apr 2024 07:51:23 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `warpack_masters::models::BattleLog::BattleLog` model
public class BattleLog : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("id")]
    public uint id;

    [ModelField("dummyCharLevel")]
    public uint dummyCharLevel;

    [ModelField("dummyCharId")]
    public uint dummyCharId;

    [ModelField("winner")]
    public FieldElement winner;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        