// Generated by dojo-bindgen on Mon, 15 Apr 2024 07:51:23 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `warpack_masters::models::BattleLog::BattleLogDetail` model
public class BattleLogDetail : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("battleLogId")]
    public uint battleLogId;

    [ModelField("id")]
    public uint id;

    [ModelField("whoTriggered")]
    public FieldElement whoTriggered;

    [ModelField("whichItem")]
    public uint whichItem;

    [ModelField("damageCaused")]
    public uint damageCaused;

    [ModelField("selfHeal")]
    public uint selfHeal;

    [ModelField("isDodged")]
    public bool isDodged;

    [ModelField("healFailed")]
    public bool healFailed;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        