// Generated by dojo-bindgen on Sat, 6 Apr 2024 07:50:28 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `warpack_masters::models::CharacterItem::CharacterItemsCounter` model
public class CharacterItemsCounter : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("count")]
    public uint count;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        