// Generated by dojo-bindgen on Sat, 6 Apr 2024 07:50:28 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;

// Type definition for `warpack_masters::models::CharacterItem::Position` struct
[Serializable]
public struct Position {
    public uint x;
    public uint y;
}


// Model definition for `warpack_masters::models::CharacterItem::CharacterItem` model
public class CharacterItem : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("id")]
    public uint id;

    [ModelField("itemId")]
    public uint itemId;

    [ModelField("where")]
    public FieldElement where;

    [ModelField("position")]
    public Position position;

    [ModelField("rotation")]
    public uint rotation;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        
