// Generated by dojo-bindgen on Mon, 15 Apr 2024 07:51:23 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;

// Type definition for `warpack_masters::models::Character::WMClass` enum
public enum WMClass {
    Warrior,
    Warlock,
}


// Model definition for `warpack_masters::models::Character::Character` model
public class Character : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("name")]
    public FieldElement name;

    [ModelField("wmClass")]
    public WMClass wmClass;

    [ModelField("gold")]
    public uint gold;

    [ModelField("health")]
    public uint health;

    [ModelField("wins")]
    public uint wins;

    [ModelField("loss")]
    public uint loss;

    [ModelField("dummied")]
    public bool dummied;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        