// Generated by dojo-bindgen on Mon, 15 Apr 2024 07:51:23 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;

// Type definition for `warpack_masters::models::Character::WMClass` enum
public enum WMClass {
    Warrior,
    Warlock,
}


// Model definition for `warpack_masters::models::DummyCharacter::DummyCharacter` model
public class DummyCharacter : ModelInstance {
    [ModelField("level")]
    public uint level;

    [ModelField("id")]
    public uint id;

    [ModelField("name")]
    public FieldElement name;

    [ModelField("wmClass")]
    public WMClass wmClass;

    [ModelField("health")]
    public uint health;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        