// Generated by dojo-bindgen on Mon, 15 Apr 2024 07:51:23 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `warpack_masters::models::Item::ItemsCounter` model
public class ItemsCounter : ModelInstance {
    [ModelField("id")]
    public FieldElement id;

    [ModelField("count")]
    public uint count;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        