// Generated by dojo-bindgen on Mon, 15 Apr 2024 07:51:23 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `warpack_masters::models::Item::Item` model
public class Item : ModelInstance {
    [ModelField("id")]
    public uint id;

    [ModelField("name")]
    public FieldElement name;

    [ModelField("width")]
    public uint width;

    [ModelField("height")]
    public uint height;

    [ModelField("price")]
    public uint price;

    [ModelField("damage")]
    public uint damage;

    [ModelField("armor")]
    public uint armor;

    [ModelField("chance")]
    public uint chance;

    [ModelField("cooldown")]
    public uint cooldown;

    [ModelField("heal")]
    public uint heal;

    [ModelField("rarity")]
    public uint rarity;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        