// Generated by dojo-bindgen on Sat, 6 Apr 2024 07:50:28 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `warpack_masters::models::Shop::Shop` model
public class Shop : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("item1")]
    public uint item1;

    [ModelField("item2")]
    public uint item2;

    [ModelField("item3")]
    public uint item3;

    [ModelField("item4")]
    public uint item4;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        
